import React, { useCallback, useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';
import { PageHeader, Spinner } from '../components/common';
import LogoSplash from '../components/common/LogoSplash';
import { useAuth } from '../hooks/useAuth';
import api from '../utils/api';

const number = new Intl.NumberFormat().format;
const statusColor = (status) => status === 'Active' ? 'var(--accent-text)' : status === 'Returned' ? 'var(--success)' : 'var(--text-secondary)';

export default function BranchAdministrationPage() {
  const navigate = useNavigate();
  const { logout } = useAuth();
  const [branches, setBranches] = useState([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const [selected, setSelected] = useState(null); const [details, setDetails] = useState(null); const [loadingDetails, setLoadingDetails] = useState(false);
  const [form, setForm] = useState({ branchName: '', branchCode: '', branchAddress: '', name: '', email: '', password: '' });
  const [edit, setEdit] = useState({ name: '', code: '', address: '' });
  const [showLogoutConfirm, setShowLogoutConfirm] = useState(false);
  const [isLoggingOut, setIsLoggingOut] = useState(false);
  const load = useCallback(async () => { try { const { data } = await api.get('/branches'); setBranches(data.branches || []); } catch (error) { const message = error.response?.data?.message || 'Unable to load branches'; toast.error(message); if (error.response?.status === 403) { await logout(); navigate('/company-admin/login', { replace: true }); } } finally { setLoading(false); } }, [logout, navigate]);
  useEffect(() => { load(); }, [load]);
  const handleLogout = async () => { setIsLoggingOut(true); await logout(); await new Promise(resolve => setTimeout(resolve, 300)); navigate('/company-admin/login', { replace: true }); };
  const review = async (branch) => { setSelected(branch); setEdit({ name: branch.name, code: branch.code, address: branch.address || '' }); setDetails(null); setLoadingDetails(true); try { const { data } = await api.get(`/branches/${branch._id}/summary`); setDetails(data.data); } catch { toast.error('Unable to load branch summary'); } finally { setLoadingDetails(false); } };
  const submit = async (event) => { event.preventDefault(); setSaving(true); try { await api.post('/branches', form); toast.success('Branch and administrator created'); setForm({ branchName: '', branchCode: '', branchAddress: '', name: '', email: '', password: '' }); load(); } catch (error) { toast.error(error.response?.data?.message || 'Unable to create branch'); } finally { setSaving(false); } };
  const saveEdit = async (event) => { event.preventDefault(); try { const { data } = await api.put(`/branches/${selected._id}`, edit); toast.success(data.message); const next = { ...selected, ...data.branch }; setSelected(next); setDetails(current => current ? { ...current, branch: data.branch } : current); load(); } catch (error) { toast.error(error.response?.data?.message || 'Unable to update branch'); } };
  const toggle = async (branch) => { try { await api.put(`/branches/${branch._id}/toggle-status`); toast.success(`Branch ${branch.isActive ? 'deactivated' : 'activated'}`); load(); if (selected?._id === branch._id) review({ ...branch, isActive: !branch.isActive }); } catch (error) { toast.error(error.response?.data?.message || 'Unable to update branch'); } };
  if (isLoggingOut) return <LogoSplash label="Signing you out..." />;
  return <div className="page-container branch-admin-page"><PageHeader title="Branch Administration" subtitle="Create, review, and manage independent branch workspaces." actions={<button type="button" className="btn-secondary company-admin-logout" onClick={() => setShowLogoutConfirm(true)}>Log out</button>} />
    {showLogoutConfirm && <div className="company-admin-modal-backdrop" role="presentation" onClick={() => setShowLogoutConfirm(false)}><div className="company-admin-modal" role="dialog" aria-modal="true" aria-labelledby="logout-confirmation-title" onClick={event => event.stopPropagation()}><h2 id="logout-confirmation-title">Log out of Company Admin?</h2><p>Your current session will end and you’ll return to the Company Admin sign-in page.</p><div className="company-admin-modal-actions"><button type="button" className="btn-secondary" onClick={() => setShowLogoutConfirm(false)}>Cancel</button><button type="button" className="btn-danger" onClick={handleLogout}>Log out</button></div></div></div>}
    <div className="branch-admin-grid" style={{ display: 'grid', gridTemplateColumns: 'minmax(280px, 390px) minmax(0, 1fr)', gap: 20, alignItems: 'start' }}>
      <form className="card" onSubmit={submit} style={{ display: 'grid', gap: 14 }}><div><h2 style={{ margin: 0, fontSize: 16 }}>New branch</h2><p style={{ margin: '4px 0 0', color: 'var(--text-secondary)', fontSize: 13 }}>New branches begin with no operational data.</p></div>{[['Branch name', 'branchName', 'text'], ['Branch code', 'branchCode', 'text'], ['Branch address', 'branchAddress', 'text'], ['Administrator name', 'name', 'text'], ['Administrator email', 'email', 'email'], ['Temporary password', 'password', 'password']].map(([label, key, type]) => <div key={key}><label className="label">{label}{key !== 'branchAddress' && ' *'}</label><input required={key !== 'branchAddress'} className="input-field" type={type} value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} /></div>)}<button className="btn-primary" disabled={saving}>{saving ? <><Spinner size="sm" /> Creating...</> : 'Create branch administrator'}</button></form>
      <div style={{ display: 'grid', gap: 20 }}><div className="card"><h2 style={{ marginTop: 0, fontSize: 16 }}>Branches</h2>{loading ? <Spinner size="sm" /> : branches.length === 0 ? <p style={{ color: 'var(--text-secondary)' }}>No branches yet.</p> : <div style={{ display: 'grid', gap: 10 }}>{branches.map(branch => <div key={branch._id} style={{ padding: 14, border: `1px solid ${selected?._id === branch._id ? 'var(--accent)' : 'var(--border)'}`, borderRadius: 10, display: 'flex', justifyContent: 'space-between', gap: 12 }}><button onClick={() => review(branch)} style={{ border: 0, background: 'transparent', cursor: 'pointer', textAlign: 'left', padding: 0, color: 'var(--text-primary)' }}><strong>{branch.name}</strong><div style={{ color: 'var(--text-secondary)', fontSize: 13, marginTop: 3 }}>{branch.code} · {branch.accountCount} accounts · {branch.isActive ? 'Active' : 'Inactive'}</div><span style={{ fontSize: 12, color: 'var(--accent-text)' }}>Review branch →</span></button><button className={branch.isActive ? 'btn-danger' : 'btn-success'} onClick={() => toggle(branch)}>{branch.isActive ? 'Deactivate' : 'Activate'}</button></div>)}</div>}</div>
      {selected && <div className="card">{loadingDetails ? <Spinner size="sm" /> : details && <><div style={{ display: 'flex', justifyContent: 'space-between', gap: 16, marginBottom: 20 }}><div><h2 style={{ margin: 0, fontSize: 18 }}>{details.branch.name} overview</h2><p style={{ margin: '4px 0 0', color: 'var(--text-secondary)', fontSize: 13 }}>Branch processes, transactions, and account activity.</p></div><button className="btn-secondary" onClick={() => setSelected(null)}>Close</button></div><form onSubmit={saveEdit} style={{ display: 'grid', gridTemplateColumns: 'repeat(3, minmax(140px, 1fr)) auto', gap: 10, alignItems: 'end', marginBottom: 22 }}><div><label className="label">Branch name</label><input className="input-field" value={edit.name} onChange={e => setEdit({ ...edit, name: e.target.value })} /></div><div><label className="label">Code</label><input className="input-field" value={edit.code} onChange={e => setEdit({ ...edit, code: e.target.value })} /></div><div><label className="label">Address</label><input className="input-field" value={edit.address} onChange={e => setEdit({ ...edit, address: e.target.value })} /></div><button className="btn-primary">Save</button></form>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(130px, 1fr))', gap: 12, marginBottom: 22 }}>{[['Cranes', details.summary.cranes], ['Attachments', details.summary.counterweights + details.summary.boomSections + details.summary.hooks], ['Active transactions', details.summary.activeTransactions], ['Completed', details.summary.completedTransactions]].map(([label, value]) => <div key={label} style={{ padding: 14, borderRadius: 10, background: 'var(--surface-2)', border: '1px solid var(--border)' }}><div style={{ fontSize: 24, fontWeight: 800 }}>{number(value)}</div><div style={{ fontSize: 12, color: 'var(--text-secondary)' }}>{label}</div></div>)}</div>
      <div style={{ display: 'grid', gridTemplateColumns: 'minmax(0, 1fr) minmax(220px, .6fr)', gap: 20 }}><div><h3 style={{ fontSize: 14 }}>Recent transactions</h3>{details.recentTransactions.length === 0 ? <p style={{ color: 'var(--text-secondary)', fontSize: 13 }}>No transactions yet — this branch is fresh.</p> : <div style={{ display: 'grid', gap: 8 }}>{details.recentTransactions.map(txn => <div key={txn._id} style={{ padding: 10, border: '1px solid var(--border)', borderRadius: 8, display: 'flex', justifyContent: 'space-between', gap: 10 }}><div><strong style={{ fontSize: 13 }}>{txn.transactionNo}</strong><div style={{ fontSize: 12, color: 'var(--text-secondary)' }}>{txn.companyName} · {txn.crane}</div></div><span style={{ fontSize: 12, color: statusColor(txn.status), fontWeight: 700 }}>{txn.status}</span></div>)}</div>}</div><div><h3 style={{ fontSize: 14 }}>Process status</h3>{details.statusBreakdown.length === 0 ? <p style={{ color: 'var(--text-secondary)', fontSize: 13 }}>No process activity yet.</p> : details.statusBreakdown.map(item => <div key={item._id} style={{ display: 'flex', justifyContent: 'space-between', padding: '9px 0', borderBottom: '1px solid var(--border-muted)' }}><span>{item._id}</span><strong>{item.count}</strong></div>)}<h3 style={{ fontSize: 14, marginTop: 20 }}>Branch accounts</h3>{details.users.map(user => <div key={user._id} style={{ fontSize: 13, padding: '6px 0' }}>{user.name} <span style={{ color: 'var(--text-secondary)' }}>({user.role})</span></div>)}</div></div></>}</div>}</div></div></div>;
}
